# Generated by Django 3.0.5 on 2020-04-06 16:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_collection_figure'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 6, 16, 39, 22, 834619, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='figure',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 6, 16, 39, 22, 834300, tzinfo=utc), verbose_name='date uploaded'),
        ),
    ]
