# Generated by Django 3.0.5 on 2020-04-06 16:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200406_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='figure',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collection',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 6, 16, 46, 1, 318656, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='figure',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 6, 16, 46, 1, 318280, tzinfo=utc), verbose_name='date uploaded'),
        ),
    ]
