# Generated by Django 3.0.5 on 2020-04-14 13:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200406_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 14, 13, 33, 54, 666727, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='collection',
            name='figures',
            field=models.ManyToManyField(related_name='collections', to='core.Figure'),
        ),
        migrations.AlterField(
            model_name='figure',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 14, 13, 33, 54, 666325, tzinfo=utc), verbose_name='date uploaded'),
        ),
    ]
